# Generated by Django 4.2.1 on 2023-05-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_pitcture_contact_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='pitcture',
            new_name='picture',
        ),
    ]
